### ISSUE TITLE
clean up publishing

### ISSUE THREAD

**Issue by JayBazuzi** [approvals/ApprovalTests.Python#180]
From `.github/workflows/publish.yml`:

```yaml
      - name: Build and publish approval_utilities
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_APPROVAL_UTILITIES }}
        run: |
          ./publish_approval_utilities.sh
      - name: Build and publish approvaltests
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.publish.py sdist bdist_wheel
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
          rm -r dist
```

- These are different but should be the same
- These depend on unpinned versions of 3rd-party modules
- Use tox
